### ISSUE TITLE
No stored boats

### ISSUE THREAD

**Issue by Ultrunz** [ESX-Org/esx_boat#11]
Just installed this. Its basically a fresh server too so everything is updated. I bought a jetski and do see it in my database.
![image](https://user-images.githubusercontent.com/13288425/54871095-c46d7980-4de1-11e9-8344-fd35d854d761.png)
but when i go to the circle for the boat spawner for the garage. i get a notification. There are no errors in my server or in my console in game neither.
![image](https://user-images.githubusercontent.com/13288425/54871106-d7804980-4de1-11e9-8db6-a3098e19c53c.png)
I am sure I have installed everything correctly and made sure my vehicleshop is up to date. I am not sure what is going on though.
Any help would be amazing, Thanks in advance

**Comment by Silvrav** [comment]
Can confirm, having the same issue. WHen you buy a boat, it dissapears and its also not in the garage

**Comment by ElPumpo** [comment]
Fix sql or check error in server console
